### PR TITLE
Adding correlationId from 4financeIT micro-infra-spring

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
e4financeIT CorrelationID PR

What I have done:
- [x] migrated CorrelationID filter (tested)
- [x] added interceptor to the registered RestTemplate to add correlationID (tested)
- [x] added autoconfiguration for correlationId (tested)
- [x] added aspect that wraps executions with correlationdId (tested)
- [x] migrated possibility to remove URI patterns from correlation id setting (tested)
- [x] created a separate module for correlationid (tested)
- [x] created a separate module for rest-template configuration setting (tested)
- [x] added copyrights
- [x] add authors

What I had to do:
- <spring-cloud.version>1.0.1.RELEASE</spring-cloud.version> because the SNAPSHOT one didn't work for Zuul and Hystrix

What has to be done:
- [] move camel support?
- [] move reactor support?

### CODE REVIEW

**Comment by spencergibb** [comment]
I can work on guava for zipkin since it's part of their api.  I'd put your correlation stuff in another module, maybe `spring-cloud-sleuth-correlation`?  That's easy enough to change anyway.  I'm not sure about if we want to put camel support here, might be something you guys continue to maintain, but I'll get @dsyer's opinion on that.

**Comment by marcingrzejszczak** [comment]
I had to ignore some `zipkin` code cause I wasn't able to build the app.

I've extracted `RestTemplate` bean setup to a new module `spring-cloud-sleuth-core` cause I need it for tests if the `ClientHttpRequestInterceptor` in the `correlation` module is properly set and its operational. It's also used in the `zipkin` module.

I don't know if the property names are ok - so please check them out :)

**Comment by spencergibb** [comment]
@marcingrzejszczak if you rebase against master you should be able to un-comment the zipkin code and it should build again

**Comment by marcingrzejszczak** [comment]
Done :)

**Comment by marcingrzejszczak** [comment]
Ok Fixed that. BTW I can't locally build this. ALl the time I have issues with Guava.

**Comment by spencergibb** [comment]
@marcingrzejszczak I can build and [travis can build](https://travis-ci.org/spring-cloud-incubator/spring-cloud-sleuth/builds/65054650).  Maybe force update your maven cache when you build? `mvn -U install`.  I had to make a change to `spring-cloud-build` to allow exceptions to the guava rule.  You probably have an old copy that still blindly blocks it.

**Comment by marcingrzejszczak** [comment]
Yeah I see that the builds pass - I have to have something done wrong on my side.

Anyways - are we ready to merge or do you want me to do sth else? If not then I can squash the commits

**Comment by spencergibb** [comment]
If you can build, I think I'm ready to merge

**Comment by marcingrzejszczak** [comment]
I still couldn't build it locally but Travis says ok :)

**Comment by marcingrzejszczak** [comment]
Once you merge - can you Tweet about us again :) ?

**Comment by marcingrzejszczak** [comment]
And (if it's not a problem) you could mention about 4financeIT in Spring Weekly ;)

**Comment by spencergibb** [comment]
Merged, I'll have to defer to @joshlong as to what goes into Spring Weekly.

**Pull request merged**
